//! Deciding what is worth reading.
//!
//! Most of the bytes in a real checkout are not code you wrote: dependencies,
//! build output, generated clients, minified bundles, lockfiles. Indexing them
//! does not just waste time, it actively poisons the result — a vendored copy of
//! a library adds thousands of plausible name matches that make every heuristic
//! guess worse.
//!
//! Every skip is recorded with a reason and shown in the UI, so coverage gaps are
//! visible rather than silent.

use cs_core::Language;
use ignore::WalkBuilder;
use std::path::{Path, PathBuf};

/// Files above this are almost always data, bundles or generated output. The
/// largest hand-written source files in well-known projects sit an order of
/// magnitude below it.
const MAX_FILE_BYTES: u64 = 2 * 1024 * 1024;

/// A line this long is a bundle, a base64 blob or a minified file. Parsing it
/// produces a syntax tree nobody can navigate.
const MAX_LINE_BYTES: usize = 5_000;

/// Directory names that are never the user's own code, even when not gitignored.
const VENDOR_DIRS: &[&str] = &[
    "node_modules",
    "vendor",
    "third_party",
    "site-packages",
    "dist-packages",
    ".venv",
    "venv",
    "target",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "__pycache__",
    ".git",
    ".svn",
    ".hg",
    ".idea",
    ".vscode",
    "Pods",
    "bower_components",
];

/// Markers that generators put near the top of what they emit.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "DO NOT EDIT",
    "This file was automatically generated",
    "Autogenerated by",
    "auto-generated",
    "@flow strict",
];

/// Filename shapes that mean "generated" regardless of contents.
const GENERATED_SUFFIXES: &[&str] = &[
    "_pb2.py",
    "_pb2_grpc.py",
    ".pb.go",
    "_pb.js",
    ".g.dart",
    ".generated.ts",
    ".gen.go",
    "_generated.go",
    ".min.js",
    ".min.css",
    ".bundle.js",
    "-lock.json",
    ".lock",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Skip {
    TooLarge,
    Minified,
    Generated,
    Binary,
    Vendored,
    /// Readable text, but no grammar for it. Still indexed for full-text search
    /// and still shown as a file node — you can find it, just not navigate it.
    Unsupported,
}

impl Skip {
    pub fn as_str(self) -> &'static str {
        match self {
            Skip::TooLarge => "too_large",
            Skip::Minified => "minified",
            Skip::Generated => "generated",
            Skip::Binary => "binary",
            Skip::Vendored => "vendored",
            Skip::Unsupported => "unsupported",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Skip::TooLarge => "zu groß",
            Skip::Minified => "minifiziert",
            Skip::Generated => "generiert",
            Skip::Binary => "binär",
            Skip::Vendored => "Fremdcode",
            Skip::Unsupported => "keine Grammatik",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Candidate {
    /// Workspace-relative, forward slashes on every platform.
    pub rel_path: String,
    pub abs_path: PathBuf,
    pub language: Option<Language>,
    pub size: u64,
    pub mtime: i64,
    /// `None` means "parse it".
    pub skip: Option<Skip>,
}

/// Walks `root`, honouring `.gitignore`, and classifies everything it finds.
///
/// Hidden files are included: `.github/workflows` and dotfile configs are often
/// exactly what explains how a project actually runs.
pub fn scan(root: &Path) -> Vec<Candidate> {
    let mut candidates = Vec::new();

    let walker = WalkBuilder::new(root)
        .hidden(false)
        .git_ignore(true)
        .git_global(true)
        .git_exclude(true)
        // Honour `.gitignore` even outside a git checkout. Plenty of what people
        // want to explore is an exported tarball or a vendored copy, and its
        // ignore file still describes what is not source.
        .require_git(false)
        .parents(true)
        .follow_links(false) // a symlink loop would walk forever
        .filter_entry(|entry| {
            let name = entry.file_name().to_string_lossy();
            !VENDOR_DIRS.contains(&name.as_ref())
        })
        .build();

    for entry in walker.flatten() {
        if !entry.file_type().is_some_and(|t| t.is_file()) {
            continue;
        }
        let abs = entry.path().to_path_buf();
        let Ok(rel) = abs.strip_prefix(root) else { continue };
        let rel_path = normalise(rel);

        let metadata = entry.metadata().ok();
        let size = metadata.as_ref().map(|m| m.len()).unwrap_or(0);
        let mtime = metadata
            .as_ref()
            .and_then(|m| m.modified().ok())
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);

        let language = language_of(&abs);
        let skip = classify(&rel_path, size, language);

        candidates.push(Candidate { rel_path, abs_path: abs, language, size, mtime, skip });
    }

    candidates
}

/// Windows path separators become forward slashes so that a workspace indexed on
/// one platform produces the same ids on another. `FileId` is derived from this
/// string, so an inconsistency here would silently invalidate every saved note.
pub fn normalise(path: &Path) -> String {
    path.components()
        .map(|c| c.as_os_str().to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("/")
}

fn language_of(path: &Path) -> Option<Language> {
    path.extension()
        .and_then(|e| e.to_str())
        .and_then(Language::from_extension)
        .or_else(|| path.file_name().and_then(|n| n.to_str()).and_then(Language::from_filename))
}

/// The cheap checks — everything decidable from the path and size alone.
fn classify(rel_path: &str, size: u64, language: Option<Language>) -> Option<Skip> {
    if rel_path.split('/').any(|part| VENDOR_DIRS.contains(&part)) {
        return Some(Skip::Vendored);
    }
    if GENERATED_SUFFIXES.iter().any(|s| rel_path.ends_with(s)) {
        return Some(Skip::Generated);
    }
    if size > MAX_FILE_BYTES {
        return Some(Skip::TooLarge);
    }
    if language.is_none() {
        return Some(Skip::Unsupported);
    }
    None
}

/// The checks that need the bytes. Called after reading, before parsing.
///
/// Returns the reason to skip, or `None` to go ahead.
pub fn inspect_contents(source: &str) -> Option<Skip> {
    if source.as_bytes().iter().take(8192).any(|b| *b == 0) {
        return Some(Skip::Binary);
    }
    if source.lines().take(400).any(|line| line.len() > MAX_LINE_BYTES) {
        return Some(Skip::Minified);
    }
    // Generator banners live in the first few lines by convention.
    let head: String = source.lines().take(8).collect::<Vec<_>>().join("\n");
    if GENERATED_MARKERS.iter().any(|m| head.contains(m)) {
        return Some(Skip::Generated);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendored_and_generated_paths_are_recognised() {
        assert_eq!(classify("node_modules/x/index.js", 100, Some(Language::JavaScript)), Some(Skip::Vendored));
        assert_eq!(classify("src/api_pb2.py", 100, Some(Language::Python)), Some(Skip::Generated));
        assert_eq!(classify("web/app.min.js", 100, Some(Language::JavaScript)), Some(Skip::Generated));
        assert_eq!(classify("src/main.py", 100, Some(Language::Python)), None);
    }

    #[test]
    fn oversized_and_unsupported_files_are_kept_but_marked() {
        assert_eq!(classify("data.py", MAX_FILE_BYTES + 1, Some(Language::Python)), Some(Skip::TooLarge));
        assert_eq!(classify("README.md", 100, None), Some(Skip::Unsupported));
    }

    #[test]
    fn minified_and_binary_contents_are_caught_after_reading() {
        let long_line = "a".repeat(MAX_LINE_BYTES + 1);
        assert_eq!(inspect_contents(&long_line), Some(Skip::Minified));
        assert_eq!(inspect_contents("ok\0bytes"), Some(Skip::Binary));
        assert_eq!(inspect_contents("// Code generated by protoc\npackage x\n"), Some(Skip::Generated));
        assert_eq!(inspect_contents("def f():\n    pass\n"), None);
    }

    #[test]
    fn paths_are_normalised_to_forward_slashes() {
        // FileId is derived from this string; if it differed per platform, an
        // index built on Windows would disagree with the same repo on Linux.
        let joined: PathBuf = ["src", "pricing", "rules.py"].iter().collect();
        assert_eq!(normalise(&joined), "src/pricing/rules.py");
    }

    #[test]
    fn scanning_a_directory_respects_gitignore_and_vendor_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join(".gitignore"), "ignored.py\n").unwrap();
        std::fs::write(root.join("kept.py"), "def f(): pass\n").unwrap();
        std::fs::write(root.join("ignored.py"), "def g(): pass\n").unwrap();
        std::fs::create_dir_all(root.join("node_modules")).unwrap();
        std::fs::write(root.join("node_modules/lib.js"), "x\n").unwrap();

        let found: Vec<String> = scan(root).into_iter().map(|c| c.rel_path).collect();
        assert!(found.contains(&"kept.py".to_string()));
        assert!(!found.iter().any(|p| p.contains("ignored.py")));
        assert!(!found.iter().any(|p| p.contains("node_modules")));
    }
}
